# Config for local development and testing

# Firebase configuration
firebase:
  project_id: sitegrupysanca
  credentials_path: configs/sitegrupysanca-firebase-adminsdk-fbsvc-ff7567bd6e.json

# Firebase collection paths/names
collections:
  texts: test_texts
  timelines: test_timelines
  images: test_images