# Config for local development and testing

#firebase collection paths/names
collections:
  texts: test_texts
  timelines: test_timelines
  images: test_images

firebase_config_path: sitegrupysanca-firebase-adminsdk-fbsvc-ff7567bd6e.json